image: gitpod/workspace-full

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - hdg.live-html-previewer@0.3.0:2Za2uotMBJrdXldl+fLonQ==
